<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" name="mock-nunit-assembly.exe" fullname="C:/Users/NUnitOrange/Downloads/NUnit-3.0.0-alpha-5b/bin/net-4.0/mock-nunit-assembly.exe" testcasecount="35" result="Failed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.064000" total="32" passed="20" failed="7" inconclusive="1" skipped="4" asserts="2" random-seed="605796550">
  <environment nunit-version="3.0.5509.17457" clr-version="4.0.30319.34014" os-version="Microsoft Windows NT 6.2.9200.0" platform="Win32NT" cwd="C:\Users\NUnitOrange\Downloads\NUnit-3.0.0-alpha-5b\bin\net-4.0" machine-name="NUnitOrange" user="NUnitOrange" user-domain="NUnitOrange" culture="en-US" uiculture="en-US" />
  <test-suite type="Assembly" id="1051" name="mock-nunit-assembly.exe" fullname="C:/Users/NUnitOrange/Downloads/NUnit-3.0.0-alpha-5b/bin/net-4.0/mock-nunit-assembly.exe" runstate="Runnable" testcasecount="35" result="Failed" site="Child" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.064000" total="32" passed="20" failed="7" inconclusive="1" skipped="4" asserts="2">
    <properties>
      <property name="_PID" value="296" />
      <property name="_APPDOMAIN" value="mock-nunit-assembly.exe" />
    </properties>
    <failure>
      <message>One or more child tests had errors</message>
    </failure>
    <test-suite type="TestSuite" id="1052" name="NUnit" fullname="NUnit" runstate="Runnable" testcasecount="35" result="Failed" site="Child" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.053000" total="32" passed="20" failed="7" inconclusive="1" skipped="4" asserts="2">
      <failure>
        <message>One or more child tests had errors</message>
      </failure>
      <test-suite type="TestSuite" id="1053" name="Tests" fullname="NUnit.Tests" runstate="Runnable" testcasecount="35" result="Failed" site="Child" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.052000" total="32" passed="20" failed="7" inconclusive="1" skipped="4" asserts="2">
        <failure>
          <message>One or more child tests had errors</message>
        </failure>
        <test-suite type="TestSuite" id="1054" name="Assemblies" fullname="NUnit.Tests.Assemblies" runstate="Runnable" testcasecount="11" result="Failed" site="Child" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.034000" total="10" passed="4" failed="4" inconclusive="1" skipped="1" asserts="0">
          <failure>
            <message>One or more child tests had errors</message>
          </failure>
          <test-suite type="TestFixture" id="1000" name="MockTestFixture" fullname="NUnit.Tests.Assemblies.MockTestFixture" runstate="Runnable" testcasecount="11" result="Failed" site="Child" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.031000" total="10" passed="4" failed="4" inconclusive="1" skipped="1" asserts="0">
            <properties>
              <property name="Category" value="FixtureCategory" />
              <property name="Description" value="Fake Test Fixture" />
            </properties>
            <failure>
              <message>One or more child tests had errors</message>
            </failure>
            <test-case id="1005" name="FailingTest" fullname="NUnit.Tests.Assemblies.MockTestFixture.FailingTest" runstate="Runnable" seed="994105559" result="Failed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.012000" asserts="0">
              <failure>
                <message>Intentional failure</message>
                <stack-trace>at NUnit.Tests.Assemblies.MockTestFixture.FailingTest()
</stack-trace>
              </failure>
            </test-case>
            <test-case id="1010" name="InconclusiveTest" fullname="NUnit.Tests.Assemblies.MockTestFixture.InconclusiveTest" runstate="Runnable" seed="118089422" result="Inconclusive" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.001000" asserts="0">
              <reason>
                <message>No valid data</message>
              </reason>
            </test-case>
            <test-case id="1001" name="MockTest1" fullname="NUnit.Tests.Assemblies.MockTestFixture.MockTest1" runstate="Runnable" seed="1998102471" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0">
              <properties>
                <property name="Description" value="Mock Test #1" />
              </properties>
            </test-case>
            <test-case id="1002" name="MockTest2" fullname="NUnit.Tests.Assemblies.MockTestFixture.MockTest2" runstate="Runnable" seed="1801850340" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0">
              <properties>
                <property name="Category" value="MockCategory" />
                <property name="Severity" value="Critical" />
                <property name="Description" value="This is a really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really, really long description" />
              </properties>
            </test-case>
            <test-case id="1003" name="MockTest3" fullname="NUnit.Tests.Assemblies.MockTestFixture.MockTest3" runstate="Runnable" seed="17143493" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.001000" asserts="0">
              <properties>
                <property name="Category" value="AnotherCategory" />
                <property name="Category" value="MockCategory" />
              </properties>
              <reason>
                <message>Succeeded!</message>
              </reason>
            </test-case>
            <test-case id="1007" name="MockTest4" fullname="NUnit.Tests.Assemblies.MockTestFixture.MockTest4" runstate="Ignored" seed="212386315" result="Skipped" label="Ignored" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.001000" asserts="0">
              <properties>
                <property name="Category" value="Foo" />
                <property name="_SKIPREASON" value="ignoring this test method for now" />
              </properties>
              <reason>
                <message>ignoring this test method for now</message>
              </reason>
            </test-case>
            <test-case id="1004" name="MockTest5" fullname="NUnit.Tests.Assemblies.MockTestFixture.MockTest5" runstate="NotRunnable" seed="458445963" result="Failed" label="Invalid" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0">
              <properties>
                <property name="_SKIPREASON" value="Method is not public" />
              </properties>
              <failure>
                <message>Method is not public</message>
              </failure>
            </test-case>
            <test-case id="1009" name="NotRunnableTest" fullname="NUnit.Tests.Assemblies.MockTestFixture.NotRunnableTest" runstate="NotRunnable" seed="501550080" result="Failed" label="Invalid" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0">
              <properties>
                <property name="_SKIPREASON" value="No arguments were provided" />
              </properties>
              <failure>
                <message>No arguments were provided</message>
              </failure>
            </test-case>
            <test-case id="1011" name="TestWithException" fullname="NUnit.Tests.Assemblies.MockTestFixture.TestWithException" runstate="Runnable" seed="1620750620" result="Failed" label="Error" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.004000" asserts="0">
              <failure>
                <message>System.Exception : Intentional Exception</message>
                <stack-trace>   at NUnit.Tests.Assemblies.MockTestFixture.MethodThrowsException()</stack-trace>
              </failure>
            </test-case>
            <test-case id="1006" name="TestWithManyProperties" fullname="NUnit.Tests.Assemblies.MockTestFixture.TestWithManyProperties" runstate="Runnable" seed="1553621128" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0">
              <properties>
                <property name="TargetMethod" value="SomeClassName" />
                <property name="Size" value="5" />
              </properties>
            </test-case>
          </test-suite>
        </test-suite>
        <test-suite type="TestFixture" id="1023" name="BadFixture" fullname="NUnit.Tests.BadFixture" runstate="NotRunnable" testcasecount="1" result="Failed" label="Invalid" site="SetUp" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.002000" total="1" passed="0" failed="1" inconclusive="0" skipped="0" asserts="0">
          <properties>
            <property name="_SKIPREASON" value="No suitable constructor was found" />
          </properties>
          <failure>
            <message>No suitable constructor was found</message>
          </failure>
          <test-case id="1024" name="SomeTest" fullname="NUnit.Tests.BadFixture.SomeTest" runstate="Runnable" seed="467836070" result="Failed" label="Invalid" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
            <failure>
              <message>OneTimeSetUp: No suitable constructor was found</message>
            </failure>
          </test-case>
        </test-suite>
        <test-suite type="TestFixture" id="1046" name="CDataTestFixure" fullname="NUnit.Tests.CDataTestFixure" runstate="Runnable" testcasecount="4" result="Failed" site="Child" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.002000" total="4" passed="2" failed="2" inconclusive="0" skipped="0" asserts="0">
          <failure>
            <message>One or more child tests had errors</message>
          </failure>
          <test-case id="1050" name="DemonstrateIllegalSequenceAtEndOfFailureMessage" fullname="NUnit.Tests.CDataTestFixure.DemonstrateIllegalSequenceAtEndOfFailureMessage" runstate="Runnable" seed="1244056055" result="Failed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0">
            <failure>
              <message>The CDATA was: &lt;![CDATA[ My &lt;xml&gt; ]]&gt;</message>
              <stack-trace>at NUnit.Tests.CDataTestFixure.DemonstrateIllegalSequenceAtEndOfFailureMessage()
</stack-trace>
            </failure>
          </test-case>
          <test-case id="1048" name="DemonstrateIllegalSequenceAtEndOfSuccessMessage" fullname="NUnit.Tests.CDataTestFixure.DemonstrateIllegalSequenceAtEndOfSuccessMessage" runstate="Runnable" seed="1026761568" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0">
            <reason>
              <message>The CDATA was: &lt;![CDATA[ My &lt;xml&gt; ]]&gt;</message>
            </reason>
          </test-case>
          <test-case id="1049" name="DemonstrateIllegalSequenceInFailureMessage" fullname="NUnit.Tests.CDataTestFixure.DemonstrateIllegalSequenceInFailureMessage" runstate="Runnable" seed="1742161598" result="Failed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0">
            <failure>
              <message>Deliberate failure to illustrate ]]&gt; in message </message>
              <stack-trace>at NUnit.Tests.CDataTestFixure.DemonstrateIllegalSequenceInFailureMessage()
</stack-trace>
            </failure>
          </test-case>
          <test-case id="1047" name="DemonstrateIllegalSequenceInSuccessMessage" fullname="NUnit.Tests.CDataTestFixure.DemonstrateIllegalSequenceInSuccessMessage" runstate="Runnable" seed="923609381" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0">
            <reason>
              <message>Deliberate failure to illustrate ]]&gt; in message </message>
            </reason>
          </test-case>
        </test-suite>
        <test-suite type="TestFixture" id="1025" name="FixtureWithTestCases" fullname="NUnit.Tests.FixtureWithTestCases" runstate="Runnable" testcasecount="4" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.013000" total="4" passed="4" failed="0" inconclusive="0" skipped="0" asserts="2">
          <test-suite type="GenericMethod" id="1031" name="GenericMethod" fullname="NUnit.Tests.FixtureWithTestCases.GenericMethod" runstate="Runnable" testcasecount="2" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="0">
            <test-case id="1029" name="GenericMethod&lt;Int32&gt;(2,4)" fullname="NUnit.Tests.FixtureWithTestCases.GenericMethod&lt;Int32&gt;(2,4)" runstate="Runnable" seed="674926834" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0" />
            <test-case id="1030" name="GenericMethod&lt;Double&gt;(9.2d,11.7d)" fullname="NUnit.Tests.FixtureWithTestCases.GenericMethod&lt;Double&gt;(9.2d,11.7d)" runstate="Runnable" seed="657009205" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0" />
          </test-suite>
          <test-suite type="ParameterizedMethod" id="1028" name="MethodWithParameters" fullname="NUnit.Tests.FixtureWithTestCases.MethodWithParameters" runstate="Runnable" testcasecount="2" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.012000" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="2">
            <test-case id="1026" name="MethodWithParameters(9,11)" fullname="NUnit.Tests.FixtureWithTestCases.MethodWithParameters(9,11)" runstate="Runnable" seed="129833087" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.012000" asserts="1" />
            <test-case id="1027" name="MethodWithParameters(2,2)" fullname="NUnit.Tests.FixtureWithTestCases.MethodWithParameters(2,2)" runstate="Runnable" seed="608442110" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="1" />
          </test-suite>
        </test-suite>
        <test-suite type="GenericFixture" id="1039" name="GenericFixture&lt;T&gt;" fullname="NUnit.Tests.GenericFixture&lt;T&gt;" runstate="Runnable" testcasecount="4" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.050000" total="4" passed="4" failed="0" inconclusive="0" skipped="0" asserts="0">
          <test-suite type="TestFixture" id="1043" name="GenericFixture&lt;Double&gt;(11.5d)" fullname="NUnit.Tests.GenericFixture&lt;Double&gt;(11.5d)" runstate="Runnable" testcasecount="2" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="0">
            <test-case id="1044" name="Test1" fullname="NUnit.Tests.GenericFixture&lt;Double&gt;(11.5d).Test1" runstate="Runnable" seed="262958866" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0" />
            <test-case id="1045" name="Test2" fullname="NUnit.Tests.GenericFixture&lt;Double&gt;(11.5d).Test2" runstate="Runnable" seed="670081083" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0" />
          </test-suite>
          <test-suite type="TestFixture" id="1040" name="GenericFixture&lt;Int32&gt;(5)" fullname="NUnit.Tests.GenericFixture&lt;Int32&gt;(5)" runstate="Runnable" testcasecount="2" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="0">
            <test-case id="1041" name="Test1" fullname="NUnit.Tests.GenericFixture&lt;Int32&gt;(5).Test1" runstate="Runnable" seed="1061146939" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0" />
            <test-case id="1042" name="Test2" fullname="NUnit.Tests.GenericFixture&lt;Int32&gt;(5).Test2" runstate="Runnable" seed="1608846388" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0" />
          </test-suite>
        </test-suite>
        <test-suite type="TestFixture" id="1016" name="IgnoredFixture" fullname="NUnit.Tests.IgnoredFixture" runstate="Ignored" testcasecount="3" result="Skipped" label="Ignored" site="SetUp" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" total="3" passed="0" failed="0" inconclusive="0" skipped="3" asserts="0">
          <properties>
            <property name="_SKIPREASON" value="BECAUSE" />
          </properties>
          <reason>
            <message>BECAUSE</message>
          </reason>
          <test-case id="1017" name="Test1" fullname="NUnit.Tests.IgnoredFixture.Test1" runstate="Runnable" seed="1196887609" result="Skipped" label="Ignored" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
            <reason>
              <message>OneTimeSetUp: BECAUSE</message>
            </reason>
          </test-case>
          <test-case id="1018" name="Test2" fullname="NUnit.Tests.IgnoredFixture.Test2" runstate="Runnable" seed="1583111997" result="Skipped" label="Ignored" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
            <reason>
              <message>OneTimeSetUp: BECAUSE</message>
            </reason>
          </test-case>
          <test-case id="1019" name="Test3" fullname="NUnit.Tests.IgnoredFixture.Test3" runstate="Runnable" seed="304199382" result="Skipped" label="Ignored" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
            <reason>
              <message>OneTimeSetUp: BECAUSE</message>
            </reason>
          </test-case>
        </test-suite>
        <test-suite type="ParameterizedFixture" id="1032" name="ParameterizedFixture" fullname="NUnit.Tests.ParameterizedFixture" runstate="Runnable" testcasecount="4" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.050000" total="4" passed="4" failed="0" inconclusive="0" skipped="0" asserts="0">
          <test-suite type="TestFixture" id="1033" name="ParameterizedFixture(42)" fullname="NUnit.Tests.ParameterizedFixture(42)" runstate="Runnable" testcasecount="2" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="0">
            <test-case id="1034" name="Test1" fullname="NUnit.Tests.ParameterizedFixture(42).Test1" runstate="Runnable" seed="1548732413" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0" />
            <test-case id="1035" name="Test2" fullname="NUnit.Tests.ParameterizedFixture(42).Test2" runstate="Runnable" seed="592696544" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0" />
          </test-suite>
          <test-suite type="TestFixture" id="1036" name="ParameterizedFixture(5)" fullname="NUnit.Tests.ParameterizedFixture(5)" runstate="Runnable" testcasecount="2" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="0">
            <test-case id="1037" name="Test1" fullname="NUnit.Tests.ParameterizedFixture(5).Test1" runstate="Runnable" seed="589179632" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0" />
            <test-case id="1038" name="Test2" fullname="NUnit.Tests.ParameterizedFixture(5).Test2" runstate="Runnable" seed="976149245" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0" />
          </test-suite>
        </test-suite>
        <test-suite type="TestSuite" id="1055" name="Singletons" fullname="NUnit.Tests.Singletons" runstate="Runnable" testcasecount="1" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.050000" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="0">
          <test-suite type="TestFixture" id="1012" name="OneTestCase" fullname="NUnit.Tests.Singletons.OneTestCase" runstate="Runnable" testcasecount="1" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="0">
            <test-case id="1013" name="TestCase" fullname="NUnit.Tests.Singletons.OneTestCase.TestCase" runstate="Runnable" seed="2083519019" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0" />
          </test-suite>
        </test-suite>
        <test-suite type="TestSuite" id="1056" name="TestAssembly" fullname="NUnit.Tests.TestAssembly" runstate="Runnable" testcasecount="1" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.050000" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="0">
          <test-suite type="TestFixture" id="1014" name="MockTestFixture" fullname="NUnit.Tests.TestAssembly.MockTestFixture" runstate="Runnable" testcasecount="1" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" total="1" passed="1" failed="0" inconclusive="0" skipped="0" asserts="0">
            <test-case id="1015" name="MyTest" fullname="NUnit.Tests.TestAssembly.MockTestFixture.MyTest" runstate="Runnable" seed="1079396103" result="Passed" start-time="2015-02-13 23:03:34Z" end-time="2015-02-13 23:03:34Z" duration="0.000000" asserts="0" />
          </test-suite>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>